### ISSUE TITLE
🐞 Compilation errors with Elixir 1.6

### ISSUE THREAD

**Issue by anildigital** [appsignal/appsignal-elixir#268]
Getting following error when tried to compile with Elixir 1.6
```
Erlang/OTP 20 [erts-9.1.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]
Elixir 1.6.0-dev (9b5af33) (compiled with OTP 20)
```

Error

```
== Compilation error in file lib/myapp_web/channels/myapp_room_channel.ex ==
** (FunctionClauseError) no function clause matching in Appsignal.Instrumentation.Decorators.__info__/1

    The following arguments were given to Appsignal.Instrumentation.Decorators.__info__/1:

        # 1
        :exports

    Appsignal.Instrumentation.Decorators.__info__/1
    lib/decorators/decorate.ex:105: Decorator.Decorate.apply_decorator/3
    lib/decorators/decorate.ex:99: Decorator.Decorate.apply_decorator/3
    (elixir) lib/enum.ex:1826: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/decorators/decorate.ex:71: Decorator.Decorate.decorate/3
    (elixir) lib/enum.ex:1826: Enum."-reduce/3-lists^foldl/2-0-"/3
    expanding macro: Decorator.Decorate.before_compile/1
    lib/standups_web/channels/standup_room_channel.ex:1: StandupsWeb.StandupRoomChannel (module)
    (elixir) lib/kernel/parallel_compiler.ex:160: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/1
```

I even don't find files such as `lib/decorators/decorate.ex` in code  to debug this issue

**Comment by tombruijn** [comment]
Hi @anildigital ,

We haven't looked at support for Elixir 1.6. It's not out yet, right?
We'll put it on our TODO list

**Comment by anildigital** [comment]
Okay. I think I am trying out Elixir 1.6 on my dev machine and would also want to deploy it on our staging environment as some goodies are neat. It won't be much effort to port to 1.6 for you folks as I can guess.

**Comment by jeffkreeftmeijer** [comment]
Hey @anildigital! 👋 Thanks for opening this issue! I've had a look and pushed a patch to the Decorator library to make sure it doesn't use `Module.__info__(:exports)` anymore. Could you try running your app on 1.6 again with an overridden dependency, to make sure this fixes your compilation error?

```
{:decorator, github: "appsignal/decorator", branch: "exports", override: true},
{:appsignal, "~> 1.0"},
```

**Comment by anildigital** [comment]
Thanks @jeffkreeftmeijer will try it.

**Comment by jeffkreeftmeijer** [comment]
We recommend `~> 1.0` to automatically update you to 1.x when you run `mix deps.update appsignal` without having to change your dependencies. The integration is backwards compatible, so any minor version bump shouldn't break instrumentation.

For this issue, locking on `~> 1.3.4` should be fine, but we're improving Phoenix 1.6 compatibility in 1.4.x and beyond, so we recommend staying on the latest official release as much as possible.

**Comment by lukaszsamson** [comment]
@jeffkreeftmeijer Your decorator patch fixes the issue.

**Comment by jeffkreeftmeijer** [comment]
Hey @lukaszsamson,

Thanks for letting me know the patch worked! I submitted it as a [pull request](https://github.com/arjan/decorator/pull/14), and @arjan released version 1.2.3 of the Decorator library, which works on Elixir master. 

I started a new branch in the AppSignal library that depends on this new version, so you can now depend on that branch (instead of overriding the decorators dependency, like I suggested [before](https://github.com/appsignal/appsignal-elixir/issues/268#issuecomment-339932988)):

```
{:appsignal, github: "appsignal/appsignal-elixir", branch: "elixir-master"}
```

We'll test compatibility with older Elixir versions on that branch before merging the version bump into master. Then, we'll keep the elixir-master branch intact to get ready for the new Elixir release, and we'll add it to the CI build matrix when a prerelease of Elixir 1.6 is published. In the meantime, we'll keep the elixir-master branch up to date with the released version of the AppSignal package.

**Comment by arjan** [comment]
You can also just do `mix deps.update decorator` in your project where you use appsignal.

**Comment by jeffkreeftmeijer** [comment]
Exactly. Sorry, I should have mentioned that. You can update the decorator dependency manually in your project instead of switching to the "elixir-master" branch. The new branch will be used for further improvements in for handling 1.6 while (or if) they come up.
