### PR TITLE
Fix compile errors on Elixir 1.6

### PR DESCRIPTION
**Pull request by mcrumm**
I thought I might be able to get the ball rolling on Elixir 1.6 support.  This PR adds Elixir 1.6.0 as a build target, and addresses the compilation errors in #296 which are the result of this manifest directory consolidation: elixir-lang/elixir@d941fe0

Please note, this does not make the lib totally ready for primetime on 1.6. Given a few test regressions, I added `elixir: 1.6.0` to the `allow_failures:` list for now.

Not sure if this would really be considered a "bugfix", so let me know if I should open this PR on a different branch.

### CODE REVIEW

**Comment by jeffkreeftmeijer** [comment]
Oh, almost forgot: the failures we're [seeing on CI](https://travis-ci.org/appsignal/appsignal-elixir/builds/331814276) in this branch are caused by changes in the backtraces reported in Elixir 1.6. These are to be expected (we had some of these when 1.5 was released), and the errors are currently caused because we're a little too strict in our tests. We'll work on getting these green for 1.6 as soon as we have reliable builds.

**Comment by lleger** [comment]
@jeffkreeftmeijer Can confirm that this seems to have fixed my issues.

**Comment by jeffkreeftmeijer** [comment]
Thanks for helping us test this patch, @lleger, and everyone else. We've just released version 1.4.7 of the integration, which includes this fix. 

You can update to it by reverting the AppSignal dependency to ` {:appsignal, "~> 1.0"}`, and running `mix deps.update`. Please be sure to open an issue or contact us via support@appsignal.com if you run into any issues!
