### ISSUE TITLE
CompileError: Plug.Conn.WrapperError.__struct__/0 is undefined

### ISSUE THREAD

**Issue by larskrantz** [appsignal/appsignal-elixir#289]
Happens when a creating a new project and having only `:app_signal`-dep in `mix.exs`, and `:plug` is not present. To reproduce:
```bash
mix new foo_appsignal 
cd foo_appsignal
```
add `{:appsignal, "~> 1.0"}` as dep in `mix.exs`.
``` bash
mix deps.get
...
mix compile
...
==> appsignal
Compiling 35 files (.ex)

== Compilation error in file lib/appsignal/error_handler.ex ==
** (CompileError) lib/appsignal/error_handler.ex:117: Plug.Conn.WrapperError.__struct__/0 is undefined, cannot expand struct Plug.Conn.WrapperError
    lib/appsignal/error_handler.ex:117: (module)
could not compile dependency :appsignal, "mix compile" failed. You can recompile this dependency with "mix deps.compile appsignal", update it with "mix deps.update appsignal" or clean it with "mix deps.clean appsignal"
```
Should be solved if changing `{:plug, ">= 1.1.0", optional: true}` to `{:plug, ">= 1.1.0"}` in `appsignal-elixir/mix.exs`.

**Comment by jeffkreeftmeijer** [comment]
Hey Lars,

Thanks for letting us know about this! This is a regression introduced by #281, by referencing the `Plug.Conn.WrapperError` module without wrapping the clause in a `Appsignal.plug?`-check. We'll add a check around it to make sure the library works without having to require Plug, and without depending on it. We'll patch this up and we'll get it ready in the next release.

In the meantime, adding Plug to your dependencies fixes this issue. Sorry about this, and thanks again for letting us know!

**Comment by larskrantz** [comment]
Thanks!

**Comment by jeffkreeftmeijer** [comment]
Hey @larskrantz,

We've released version 1.4.6 yesterday, which includes the patch for this issue. Could you try upgrading to that by running `mix deps.update appsignal` and removing the Plug dependency to see if the new version works for you without having to depend on Plug? Thanks for reporting this issue!

**Comment by larskrantz** [comment]
Sorry for late reply @jeffkreeftmeijer -- but it works fine compiling now!
Thanks /Lars
